version: "3"
services:
    jupyter:
        image: jupyter/scipy-notebook
        container_name: "my_jupyter"
        ports:
            - 8888:8888
    postgres:
        image: postgres
        container_name: "my_postgres"
        ports:
            - 5432:5432
        environment:
            - SHARED_PASSWORD=password
            - POSTGRES_PASSWORD=secret
        volumes:
            - ./scripts/:/docker-entrypoint-initdb.d/
            - pg_data:/var/lib/postgresql/data
volumes:
    pg_data:
